### PR TITLE
Vector PRF

### PR DESCRIPTION
**Pull request by cmacdonald**
WIP.

Our results:
image

Results from Pyserini:
image

(I think they use FAISS as a retrieval backend)

### CODE REVIEW

**Comment by seanmacavaney** [comment]
Looks great, thanks! I prefer class-based Transformer definitions for stuff that isn't ad hoc. I'm happy to convert it to that format if you're okay with it?

**Comment by cmacdonald** [comment]
I guess the advantage of a transformer is that its parameters can be tuned in a gridsearch.

I think we should commit a notebook to the examples folder. I have one that can be associted.

**Comment by seanmacavaney** [comment]
Sounds good. Yeah, there are other benefits too, like you can get a clearer repr.

I think more extensive tests would also be good. I just put in one basic one to make sure I didn’t mess something up in the new version.

**Comment by cmacdonald** [comment]
sure.

**Comment by seanmacavaney** [comment]
Yeah, I'd rather not have any more `transform_*()` definitions in `pt.Transformer` if possible.

I'm also no stranger to just doing a `groupby` in the definition. It ends up being a few lines of boilerplate, but nothing crazy.

**Review by seanmacavaney — APPROVED** [review]

**Comment by seanmacavaney** [comment]
Alright, I'm happy with this version.

I went ahead and added `@pta.transform.by_query` to alpha. I'm happy to discuss further for a version to include in the core API, but I didn't want to hold up this PR on those discussions.

**Comment by cmacdonald** [comment]
ok, I'll make a separate PR with a notebook.

**Comment by cmacdonald** [comment]
Going to merge it?

**Pull request merged**
