### PR TITLE
refactor out a generic biencoder class, provide example using contriever

### PR DESCRIPTION
**Pull request by cmacdonald**

### CODE REVIEW

**Comment by seanmacavaney** [comment]
Whoops, looks like we've covered a lot of the same ground... In the [refactor branch](https://github.com/terrierteam/pyterrier_dr/tree/refactor) I have:

 - Generic Bi-Encoder: https://github.com/terrierteam/pyterrier_dr/blob/refactor/pyterrier_dr/biencoder.py
 - Bi-Encoders from SBERT: https://github.com/terrierteam/pyterrier_dr/blob/refactor/pyterrier_dr/sbert_models.py
 - Bi-Encoders from Huggingface: https://github.com/terrierteam/pyterrier_dr/blob/refactor/pyterrier_dr/hgf_models.py

**Comment by cmacdonald** [comment]
ah, yes.  A staticmethod for easier specification of encoders might be nice too then?

**Comment by seanmacavaney** [comment]
Yeah, so that's what `VARIANTS` defines. E.g.,

```
Ance.firstp()
TasB.dot()
RetroMAE.msmarco_distill()
```

**Comment by seanmacavaney** [comment]
(or maybe I don't understand what you're suggesting.)

**Comment by cmacdonald** [comment]
I'm proposing being able to set the encode methods without creating a sub-class. Much like pt.apply helps do Transformers.

Lets say I have to encode like this:

```python
def encode(self, texts, max_length=32):
  results = []
  with torch.no_grad():
      for chunk in chunked(texts, self.batch_size):
          inps = self.tokenizer([q for q in chunk], return_tensors='pt', padding=True, truncation=True, max_length=max_length)
          if self.cuda:
              inps = {k: v.cuda() for k, v in inps.items()}
          res = self.model(**inps)
          results.append(res.cpu().numpy())
  return np.concatenate(results, axis=0)
```

I could instantiate the model something like this:
```python
contriever_reranker = BiEncoder.from_model(
  Contriever.from_pretrained(model_name),
  tokenizer = model_name,
  encode_queries = encode,
  encode_docs = partial(encode, max_length=200)
).scorer()
```

**Comment by cmacdonald** [comment]
I'd like more of the boilerplate typical stuff done if possible (tokenization, **batching**, numpy etc), but I guess some models differ in how they do tokenisation.
Contriever is a huggingface model, so perhaps it doesnt as much special handling. But I think you catch the drift.

**Comment by seanmacavaney** [comment]
Hmmm, so maybe the static method belongs under the implementation-specific ones then? E.g., `HuggingfaceBiEncoder.from_model(model, tokenizer, encode_query, encode_doc)` Because each of the implementations will abstract away different things. SBERT, for instance, takes strings directly and does its own tokenisation internally.

Dropping some of the batching, concat'ing, etc. boilerplate seems reasonable to abstract out in all cases, though.

```python
class BiEncoder(pt.Transformer):
    ...
    def encode_queries(self, texts: Iter[str]) -> np.array:
        results = []
        for batch in chunked(texts, self.batch_size):
            results.append(self._encode_queries_batch(batch))
        return np.concatenate(results, axis=0)
    def _encode_queries_batch(self, texts: List[str]) -> np.array:
        raise NotImplementedError()
```

And on the off-chance that there are cases where it shouldn't apply, you could just override `encode_queries` and `encode_docs` instead.

**Comment by seanmacavaney** [comment]
Covered by the current main branch.

**Pull request closed without merging**
