### PR TITLE
add E5 as SBertBiEncoder

### PR DESCRIPTION
**Pull request by cmacdonald**
This adds support for the E5 biencoder model, which @fangjy6 has been using.

### CODE REVIEW

**Comment by cmacdonald** [comment]
@fangjy6 will add more model variants, and check the score given by the model with his own setting

**Comment by seanmacavaney** [comment]
Looks great, thanks!

I suspect the normalization step isn't needed, at least for `e5-base-v2` -- from what I can tell, sentence-transformers already does it: https://huggingface.co/intfloat/e5-base-v2/blob/main/modules.json#L15-L18

**Comment by cmacdonald** [comment]
> I suspect the normalization step isn't needed, at least for e5-base-v2 -- from what I can tell, sentence-transformers already does it for this model, based on its configuration: https://huggingface.co/intfloat/e5-base-v2/blob/main/modules.json#L15-L18tcol

I've checked empircally on colab
image

**Comment by seanmacavaney** [comment]
Interesting -- worth keeping it then! Thanks for checking it.

**Comment by cmacdonald** [comment]
```
self = E5.base().doc_encoder(), texts = Series([], Name: text, dtype: object)
batch_size = None

    def encode(self, texts, batch_size=None) -> np.array:
>       return self.bi_encoder_model.encode_docs(texts, batch_size=batch_size or self.batch_size)
E       TypeError: _sbert_encode() missing 1 required positional argument: 'texts'
```

i dont follow whats gone wrong here.

**Comment by seanmacavaney** [comment]
Weird, yeah. Maybe it’s not binding self to the first argument when it’s a partial?

**Comment by cmacdonald** [comment]
Does the other instance work?

In PyT, I had to use a function called bind:
https://github.com/terrier-org/pyterrier/blob/master/pyterrier/apply.py#L7-L18

**Comment by cmacdonald** [comment]
https://stackoverflow.com/a/16626797 
apparently `functools.partialmethod()` exists

**Comment by cmacdonald** [comment]
So the test case /should/ now work - we'll refine the test case tomorrow; 
@seanmacavaney I sketched documentation for sbert as part of this PR that you may wish to review.

**Comment by seanmacavaney** [comment]
> I sketched documentation for sbert as part of this PR that you may wish to review.

Looks great, minor edit and added to the toc.

**Pull request merged**
